import type { IFlight } from "./findbddom";

export const NPdomFlight:Array<IFlight> = [
  {
    airportCode: "BDP",
    airportName: "Bhadrapur Airport",
    cityCode: "BDP",
    cityName: "Bhadrapur",
    format: "BDP, Bhadrapur",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "BGL",
    airportName: "Balewa Airport",
    cityCode: "BGL",
    cityName: "Baglung",
    format: "BGL, Balewa",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "BHP",
    airportName: "Bhojpur Airport",
    cityCode: "BHP",
    cityName: "Bhojpur",
    format: "BHP, Bhojpur",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "BHR",
    airportName: "Bharatpur Airport",
    cityCode: "BHR",
    cityName: "Bharatpur",
    format: "BHR, Bharatpur",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "BIR",
    airportName: "Biratnagar Airport",
    cityCode: "BIR",
    cityName: "Biratnagar",
    format: "BIR, Biratnagar",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "BIT",
    airportName: "Baitadi Airport",
    cityCode: "BIT",
    cityName: "Baitadi",
    format: "BIT, Baitadi",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "BJH",
    airportName: "Bajhang Airport",
    cityCode: "BJH",
    cityName: "Bajhang",
    format: "BJH, Bajhang",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "BJU",
    airportName: "Bajura Airport",
    cityCode: "BJU",
    cityName: "Bajura",
    format: "BJU, Bajura",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "BWA",
    airportName: "Gautam Buddha Airport",
    cityCode: "BWA",
    cityName: "Siddharthanagar",
    format: "BWA, Gautam Buddha",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "DAP",
    airportName: "Darchula Airport",
    cityCode: "DAP",
    cityName: "Darchula",
    format: "DAP, Darchula",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "DHI",
    airportName: "Dhangadhi Airport",
    cityCode: "DHI",
    cityName: "Dhangadhi",
    format: "DHI, Dhangadhi",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "DNP",
    airportName: "Tribhuvannagar Airport",
    cityCode: "DNP",
    cityName: "Tribhuwannagar",
    format: "DNP, Tribhuvannagar",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "DOP",
    airportName: "Dolpa Airport",
    cityCode: "DOP",
    cityName: "Dolpa",
    format: "DOP, Dolpa",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "FEB",
    airportName: "Sanfebagar Airport",
    cityCode: "FEB",
    cityName: "Sanfebagar",
    format: "FEB, Sanfebagar",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "GKH",
    airportName: "Palungtar Airport",
    cityCode: "GKH",
    cityName: "Gorkha",
    format: "GKH, Palungtar",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "IMK",
    airportName: "Simikot Airport",
    cityCode: "IMK",
    cityName: "Simikot",
    format: "IMK, Simikot",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "JIR",
    airportName: "Jiri Airport",
    cityCode: "JIR",
    cityName: "Jiri",
    format: "JIR, Jiri",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "JKR",
    airportName: "Janakpur Airport",
    cityCode: "JKR",
    cityName: "Janakpur",
    format: "JKR, Janakpur",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "JMO",
    airportName: "Jomsom Airport",
    cityCode: "JMO",
    cityName: "Jomsom",
    format: "JMO, Jomsom",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "JUM",
    airportName: "Jumla Airport",
    cityCode: "JUM",
    cityName: "Jumla",
    format: "JUM, Jumla",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "KEP",
    airportName: "Nepalgunj Airport",
    cityCode: "KEP",
    cityName: "Nepalgunj",
    format: "KEP, Nepalgunj",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "KTM",
    airportName: "Tribhuvan International Airport",
    cityCode: "KTM",
    cityName: "Kathmandu",
    format: "KTM, Tribhuvan International",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "LDN",
    airportName: "Lamidanda Airport",
    cityCode: "LDN",
    cityName: "Lamidanda",
    format: "LDN, Lamidanda",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "LTG",
    airportName: "Langtang Airport",
    cityCode: "LTG",
    cityName: "Langtang",
    format: "LTG, Langtang",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "LUA",
    airportName: "Tenzing-Hillary Airport",
    cityCode: "LUA",
    cityName: "Lukla",
    format: "LUA, Tenzing-Hillary",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "MEY",
    airportName: "Meghauli Airport",
    cityCode: "MEY",
    cityName: "Meghauli",
    format: "MEY, Meghauli",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "NGX",
    airportName: "Manang Airport",
    cityCode: "NGX",
    cityName: "Manang",
    format: "NGX, Manang",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "PKR",
    airportName: "Pokhara Airport",
    cityCode: "PKR",
    cityName: "Pokhara",
    format: "PKR, Pokhara",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "PPL",
    airportName: "Phaplu Airport",
    cityCode: "PPL",
    cityName: "Phaphlu",
    format: "PPL, Phaplu",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "RHP",
    airportName: "Ramechhap Airport",
    cityCode: "RHP",
    cityName: "Ramechhap",
    format: "RHP, Ramechhap",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "RJB",
    airportName: "Rajbiraj Airport",
    cityCode: "RJB",
    cityName: "Rajbiraj",
    format: "RJB, Rajbiraj",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "RPA",
    airportName: "Rolpa Airport",
    cityCode: "RPA",
    cityName: "Rolpa",
    format: "RPA, Rolpa",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "RUK",
    airportName: "Chaurjahari Airport",
    cityCode: "RUK",
    cityName: "Rukumkot",
    format: "RUK, Chaurjahari",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "RUM",
    airportName: "Rumjatar Airport",
    cityCode: "RUM",
    cityName: "Rumjatar",
    format: "RUM, Rumjatar",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "SIF",
    airportName: "Simara Airport",
    cityCode: "SIF",
    cityName: "Simara",
    format: "SIF, Simara",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "SIH",
    airportName: "Silgadhi Airport",
    cityCode: "SIH",
    cityName: "Dipayal Silgadhi",
    format: "SIH, Silgadhi",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "SKH",
    airportName: "Surkhet Airport",
    cityCode: "SKH",
    cityName: "Surkhet",
    format: "SKH, Surkhet",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "SYG",
    airportName: "Syangboche Airport",
    cityCode: "SYG",
    cityName: "Namche Bazaar",
    format: "SYG, Syangboche",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "TMI",
    airportName: "Tumlingtar Airport",
    cityCode: "TMI",
    cityName: "Tumlingtar",
    format: "TMI, Tumlingtar",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "TPJ",
    airportName: "Taplejung Airport",
    cityCode: "TPJ",
    cityName: "Taplejung",
    format: "TPJ, Taplejung",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "TPU",
    airportName: "Tikapur Airport",
    cityCode: "TPU",
    cityName: "Tikapur",
    format: "TPU, Tikapur",
    countryCode: "NP",
    countryName: "Nepal",
  },
  {
    airportCode: "XMG",
    airportName: "Mahendranagar Airport",
    cityCode: "XMG",
    cityName: "Bhimdatta",
    format: "XMG, Mahendranagar",
    countryCode: "NP",
    countryName: "Nepal",
  },
];


export const findnpdom = (airportCode: string) => {
  return NPdomFlight.some((item) =>
    item.format
      .replace(/\s+/g, " ")
      .trim()
      .toLocaleLowerCase()
      .includes(airportCode.replace(/\s+/g, " ").trim().toLocaleLowerCase())
  );
};