export {
  AUTH_PAGE_ROUTES,
  isAuthRoute,
  commonProtectedRoutes,
  superadminProtectedRoutes,
  adminProtectedRoutes,
  b2bProtectedRoutes,
  b2cProtectedRoutes,
  isRouteMatches,
  getRouteOwner,
  getDefaultDashboardRoute,
  isValidRedirectForRole,
  resolvePostLoginRedirect,
  ROUTE_DEPARTMENT,
  getRequiredDepartments,
  canAccessRoute,
  ADMIN_DEPARTMENT_ROUTES,
  getAdminRequiredDepartments,
  isAdminReadOnlyView,
} from "./routes";
